# Generated by Django 5.2 on 2025-04-15 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodbankWorker',
            fields=[
                ('bb_worker_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('bb_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=512, unique=True)),
                ('bloodbank_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.bloodbankworker')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=512)),
                ('phone', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('blood_type', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('phone', 'email')},
            },
        ),
        migrations.CreateModel(
            name='HealthcareWorker',
            fields=[
                ('hc_worker_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='HealthCenter',
            fields=[
                ('hc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=512)),
                ('healthcare_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.healthcareworker')),
            ],
            options={
                'unique_together': {('address',)},
            },
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('dono_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('donation_sate', models.DateField()),
                ('sent_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.bloodbank')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.donor')),
                ('health_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.healthcenter')),
            ],
        ),
        migrations.CreateModel(
            name='DonorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.donor')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.message')),
            ],
            options={
                'unique_together': {('donor', 'message')},
            },
        ),
    ]
