# Generated by Django 5.2 on 2025-04-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='bloodbank_worker',
        ),
    ]
