# Generated by Django 5.2 on 2025-04-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0002_remove_bloodbank_bloodbank_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcenter',
            name='healthcare_worker',
        ),
    ]
