# Generated by Django 5.2 on 2025-04-15 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0003_remove_healthcenter_healthcare_worker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='healthcareworker',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bloodbankworker',
            name='blood_bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cbobbs.bloodbank'),
        ),
        migrations.AddField(
            model_name='healthcareworker',
            name='health_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cbobbs.healthcenter'),
        ),
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('name', 'email')},
        ),
    ]
