# Generated by Django 5.2 on 2025-04-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0004_alter_healthcareworker_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
    ]
