# Generated by Django 5.2 on 2025-04-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0005_rename_donations_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(default='Blood Bank', max_length=50),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='phone',
            field=models.CharField(default='9999999999', max_length=10),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='name',
            field=models.CharField(default='Health Center', max_length=50),
        ),
    ]
