# Generated by Django 5.2 on 2025-04-15 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0006_bloodbank_name_bloodbank_phone_healthcenter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donation_sate',
            new_name='donation_date',
        ),
        migrations.AddField(
            model_name='donation',
            name='blood_type',
            field=models.CharField(default='n/a', max_length=5),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appt_date', models.DateField(default=django.utils.timezone.now)),
                ('appt_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.bloodbank')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.donor')),
            ],
        ),
    ]
