# Generated by Django 5.2 on 2025-04-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0007_rename_donation_sate_donation_donation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcenter',
            name='hc_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
