# Generated by Django 5.2 on 2025-04-16 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0008_alter_healthcenter_hc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='health_center',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbobbs.healthcenter'),
        ),
    ]
