# Generated by Django 4.2.20 on 2025-04-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0008_alter_healthcenter_hc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbankworker',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=50),
        ),
        migrations.AddField(
            model_name='healthcareworker',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=50),
        ),
    ]
