# Generated by Django 4.2.20 on 2025-04-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0009_bloodbankworker_role_healthcareworker_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbankworker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='healthcareworker',
            name='password',
        ),
    ]
