# Generated by Django 4.2.20 on 2025-04-18 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbobbs', '0012_alter_bloodbankworker_bb_worker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankworker',
            name='bb_worker_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bbworker', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthcareworker',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='healthcareworker',
            name='hc_worker_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hcworker', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthcareworker',
            name='name',
            field=models.CharField(max_length=310),
        ),
    ]
