# Generated by Django 4.2.20 on 2025-04-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0013_alter_bloodbankworker_bb_worker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbankworker',
            name='blood_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.bloodbank'),
        ),
        migrations.AlterField(
            model_name='healthcareworker',
            name='health_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.healthcenter'),
        ),
    ]
