# Generated by Django 4.2.20 on 2025-04-18 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbobbs', '0014_alter_bloodbankworker_blood_bank_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('name', 'email')},
        ),
        migrations.AlterField(
            model_name='donor',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='donor',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='donor', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('phone', 'email'), ('name', 'email')},
        ),
    ]
