# Generated by Django 5.2 on 2025-04-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0009_alter_donation_health_center'),
        ('cbobbs', '0015_alter_donor_unique_together_alter_donor_address_and_more'),
    ]

    operations = [
    ]
