# Generated by Django 4.2.20 on 2025-04-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0016_merge_20250421_0647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('phone', 'email')},
        ),
        migrations.AlterField(
            model_name='donation',
            name='health_center',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbobbs.healthcenter'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
