# Generated by Django 5.2 on 2025-04-23 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0018_alter_donor_blood_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='sent_at',
            new_name='transfer_date',
        ),
    ]
