# Generated by Django 4.2.20 on 2025-04-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0019_rename_sent_at_donation_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='admin_key',
            field=models.CharField(default='admin', max_length=5),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='admin_key',
            field=models.CharField(default='admin', max_length=5),
        ),
        migrations.AddField(
            model_name='healthcenter',
            name='phone',
            field=models.CharField(default='9999999999', max_length=10),
        ),
    ]
