# Generated by Django 4.2.20 on 2025-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0020_bloodbank_admin_key_healthcenter_admin_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='medical_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
