# Generated by Django 4.2.20 on 2025-04-24 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbobbs', '0022_remove_donation_medical_notes_donor_medical_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('recipient_type', models.CharField(choices=[('donor', 'Donor'), ('blood_bank_worker', 'Blood Bank Worker'), ('hc_worker', 'Healthcare Worker')], max_length=20)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbobbs.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DonorMessage',
        ),
    ]
