# Generated by Django 4.2.20 on 2025-04-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0023_messagerecipient_delete_donormessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerecipient',
            name='read',
        ),
    ]
