# Generated by Django 4.2.20 on 2025-04-24 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0024_remove_messagerecipient_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='health_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbobbs.healthcenter'),
        ),
    ]
