# Generated by Django 4.2.20 on 2025-04-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0025_alter_donation_health_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='city',
            field=models.CharField(default='Charlotte', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='state',
            field=models.CharField(default='North Carolina', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='zipcode',
            field=models.CharField(default='28277', max_length=10),
        ),
    ]
