# Generated by Django 4.2.20 on 2025-04-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0026_bloodbank_city_bloodbank_state_bloodbank_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
