# Generated by Django 4.2.20 on 2025-04-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('cbobbs', '0028_remove_bloodbank_latitude_remove_bloodbank_longitude_and_more'), ('cbobbs', '0029_remove_bloodbank_location_bloodbank_latitude_and_more')]

    dependencies = [
        ('cbobbs', '0027_bloodbank_latitude_bloodbank_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='longitude',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
