# Generated by Django 4.2.20 on 2025-04-25 03:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0027_bloodbank_latitude_bloodbank_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bloodbank',
            name='longitude',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
