# Generated by Django 4.2.20 on 2025-04-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbobbs', '0028_remove_bloodbank_latitude_remove_bloodbank_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='location',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
